### ISSUE TITLE
[Chapter] coin selection

### ISSUE THREAD

**Issue by jnewbery** [bitcoinops/scaling-book#13]
https://en.bitcoin.it/wiki/Techniques_to_reduce_transaction_fees#Change_avoidance

Could include a field report on 'predictive fee management': https://www.coindesk.com/bitcoin-companies-slash-fees-cutting-edge-tech or https://medium.com/simplexum/on-predictive-utxo-management-974be49506ca

**Comment by moneyball** [comment]
Another resource: https://medium.com/@lopp/the-challenges-of-optimizing-unspent-output-selection-a3e5d05d13ef

**Comment by Xekyo** [comment]
Interested in this topic. Some ideas to cover:

- Intro
- Problem Description
- Dimensions of the Problem:
  - Short term fees vs long term fees
  - Privacy
  - Individual Usage Pattern
  - Global UTXO Set
- Significance of omitting change outputs
- Simple workable solution: Random Selection
- Heuristic-based UTXO Management, e.g. Branch and Bound
- Coin Control
- Additional UTXO Management Strategies (link to consolidation and batching)
- Outlook: New Address formats

**Comment by jnewbery** [comment]
That outline looks fine. I don't think you've missed anything. Some comments:

> Coin Control
I'd refer to this as 'manual coin selection' or 'user coin selection'.

> Additional UTXO Management Strategies (link to consolidation and batching)
Yes, this should just be a link to the other chapters to ensure that we're not repeating content.

> Outlook: New Address formats
As discussed, the important metric here is value/vbyte. The type of scriptPubKey (and by extension the txIn/witness required to spend it) obviously affects the vbyte side of that ratio, but beyond that we're not interested in the scriptPubKey type when selecting coins.
