### ISSUE TITLE
[Chapter] Urgency tradeoffs

### ISSUE THREAD

**Issue by jnewbery** [bitcoinops/scaling-book#15]
https://en.bitcoin.it/wiki/Techniques_to_reduce_transaction_fees#Patient_spending

**Comment by harding** [comment]
Claiming this topic.  Proposed outline:

- Describe the market for block space (expanded version of https://en.bitcoin.it/wiki/Miner_fees#The_market_for_block_space )
- Explain the idea of paying for urgency
- Quantify probable savings using recent data (e.g. the data used at https://github.com/bitcoinops/scaling-book/pull/24/files#diff-e9ba84d872ddd5e4388022fcd7ab047fR507 ); maybe also try to get some data from the Dec '17/Jan '18 fee spike
- Describe how enabling RBF or preparing to use CPFP gives you the ability to start with a low feerate but increase it later if necessary
- Suggest a basic UI for allowing users to choose their preferred urgency / cost tradeoff.
- Evaluate combining non-urgent payments with payment batching

**Comment by harding** [comment]
Unclaiming this topic.  Despite putting in a number of hours, I haven't made any real progress on writing this chapter and I'm overall unhappy with the quality of my writing in the previous two scaling book chapters I've written, so I'm going to try to redirect my attention to other tasks where I can (hopefully) make more progress.  Sorry for the disappointment.  :-(
