### ISSUE TITLE
[Chapter] Lightning network

### ISSUE THREAD

**Issue by jnewbery** [bitcoinops/scaling-book#16]
Fully describing how the to integrate the lightning network may be beyond the scope of this book, but it's definitely worth having a high-level overview, with references for where to go for more details.

https://en.bitcoin.it/wiki/Techniques_to_reduce_transaction_fees#Payment_channels

**Comment by moneyball** [comment]
It seems there is potential to address various scaling challenges with LN including
- channel rebalancing (on-chain, circular payments, etc.)
- channel factories
- using Schnorr

**Comment by harding** [comment]
I don't have any problem providing information about possible future improvements, but I would encourage trying to keep the book focused on things companies can deploy immediately and without much engineering effort.  My rule of thumb would be to focus on things that can be done using current major open source software and no more than 100 lines of custom code.

**Comment by PierreRochard** [comment]
For circular payment channel rebalancing I've tested @C-Otto's [rebalance-lnd](https://github.com/C-Otto/rebalance-lnd) script, so it can be done today though just from anecdotal data I think on-chain rebalancing is going to generally be less expensive until there's on-chain fee pressure.

**Comment by harding** [comment]
@PierreRochard thanks for the info!  On that subject, I was also pondering Osuntokun's comment yesterday that rebalancing might not be particularly important after payment splitting matures (which seems like the umpteenth benefit of that already-cool feature): https://twitter.com/roasbeef/status/1102709883596496896
